site_name: 公考笔记
site_url: https://gsl-web.github.io/-/
repo_url: https://github.com/gsl-web/-/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.tracking
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换深色模式
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换浅色模式

docs_dir: .

nav:
  - 首页: README.md
  - 判断推理: 判断推理/
  - 数量关系: 数量关系/
  - 言语理解: 言语理解/

markdown_extensions:
  - toc:
      permalink: true
      depth: 4
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences